#! /bin/sh

export EDITOR=nvim

pgrep -x sxhkd > /dev/null || sxhkd &

xinput --set-prop "ELAN1300:00 04F3:3087 Touchpad" "libinput Natural Scrolling Enabled" 1 &
setxkbmap -option grp:alt_shift_toggle us,es &
#feh --bg-fill /home/mura/Pictures/Walls/wallhaven-z881xv.png
#feh --bg-fill /home/mura/Pictures/Walls/wallhaven-76yzy3.jpg
feh --bg-fill /home/mura/Pictures/Walls/wallhaven-n6926w.jpg
xsetroot -cursor_name left_ptr &
picom -f -b &
light -S 50 &
$HOME/.config/polybar/bspwmlaunch.sh &
$HOME/.config/scripts/spotifywm &
xfce4-power-manager &
blueberry-tray &
nm-applet &

bspc monitor eDP -d I II III IV V VI VII VIII IX X

bspc config border_width         	4
# Dracula theme
#bspc config normal_border_color         '#44475a'
#bspc config active_border_color         '#bd93f9'
#bspc config focused_border_color        '#ff79c6'
#bspc config presel_feedback_color       '#6272a4'

# Monokai soda theme
#bspc config normal_border_color		'#303030'
#bspc config active_border_color		'#1a1a1a'
#bspc config focused_border_color	'#98e924'
#bspc config presel_feedback_color	'#e6db74'

bspc config normal_border_color         '#1a1a1a'
bspc config active_border_color         '#1a1a1a'
bspc config focused_border_color        '#1a1a1a'
bspc config presel_feedback_color       '#e6db74'

# Nord theme
#bspc config normal_border_color		'#2e3440'
#bspc config active_border_color		'#3b4252'
#bspc config focused_border_color	'#88c0d0'
#bspc config presel_feedback_color	'#434c5e'
#bspc config top_padding 		30

bspc config top_padding			30
bspc config bottom_padding 		0
bspc config left_padding 		0
bspc config right_padding 		0

bspc config honor_size_hints		true

bspc config window_gap           	10

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

bspc config ignore_ewmh_focus 		false

bspc config focus_follows_pointer true

bspc rule -a firefox desktop='^1' follow=on
bspc rule -a kitty desktop='^2' follow=on
bspc rule -a Alacritty desktop='^2' follow=on
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a Soffice desktop='^4' follow=on
bspc rule -a qBittorrent desktop='^6'
bspc rule -a "Microsoft Teams - Preview" desktop='^7'
bspc rule -a discord desktop='^7'
bspc rule -a Anydesk desktop='^8'
bspc rule -a TeamViewer desktop='^8'
bspc rule -a mpv desktop='^9' state=floating follow=on focus=on
bspc rule -a Spotify desktop='^10'

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
